name: Bitcoin Data Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # tiap jam

jobs:
  bitcoin_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r project/requirements.txt

      - name: Run Bitcoin Data Pipeline
        run: |
          python project/src/run_pipeline.py